FROM jupyter/pyspark-notebook:aarch64-spark-3.5.0

USER root
RUN apt-get update && apt-get install -y openjdk-11-jdk
USER jovyan

# Install Delta Lake dependencies
COPY ./requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt