FROM jupyter/pyspark-notebook:spark-3.4.0

USER root
RUN apt-get update && apt-get install -y openjdk-11-jdk

# not to run as root anything else
USER jovyan

# Install Delta Lake dependencies
COPY ./requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt \ 
    && rm -rf /tmp/requirements.txt

# keep the container running for interactive use
ENTRYPOINT ["tail", "-f", "/dev/null"] 